spring:
  application:
    name: jwizard-api
  banner:
    location: classpath:spring/banner.txt
  mvc:
    throw-exception-if-no-handler-found: true
  config:
    import:
      - optional:vault://
  cloud:
    vault:
      uri: ${ENV_VAULT_URI:http://localhost:8761}
      token: ${ENV_VAULT_TOKEN}
      authentication: TOKEN
      kv:
        backend: jwizard
        default-context: common
        application-name: ${spring.application.name}
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: ${ENV_MONGO_PORT:8762}
      database: jwizard
      username: ${V_MONGODB_USERNAME}
      password: ${V_MONGODB_PASSWORD}
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

jwizard:
  i18n:
    default-locale: en-US
    available-locales:
      - en-US
      - pl
    locale-bundles:
      - i18n-command/messages
  command:
    resource-file: classpath:assets/bot-commands.json
  security:
    jwt-secret: ${V_JWT_SECRET_KEY:4c9RiR9iwCMTC7NVLr69yP8D5U9PopevQWgGyrNFHkDvO60kzo}
    life:
      access-minutes: 5
      refresh-days: 30
