jwizard:
  security:
    jwt-audience:
      standalone-client: proxy://standalone-prod
      web-client: https://jwizard.pl
    jwt-issuer: https://api.jwizard.pl
  guild:
    defaults:
      legacy-prefix: '$'

logging:
  file:
    path: .log/prod
