spring:
  application:
    name: jwizard-api
  banner:
    location: classpath:spring/banner.txt
  mvc:
    throw-exception-if-no-handler-found: true
    log-resolved-exception: off
  datasource:
    username: ${V_MYSQL_USERNAME}
    password: ${V_MYSQL_PASSWORD}
  web:
    resources:
      add-mappings: false
  cache:
    jcache:
      config: classpath:spring/ehcache.xml

jwizard:
  deployment:
    build-version: ${JWIZARD_API_BUILD_VERSION:DEVELOPMENT}
    last-build-date: ${JWIZARD_API_BUILD_DATE:DEVELOPMENT}
  github-api:
    url: https://api.github.com
    organization-name: jwizard-bot
  i18n:
    default-locale: pl
    available-locales:
      - en
      - pl
    locale-bundles:
      - i18n-feature/messages

logging:
  level:
    org.springframework.web.servlet.PageNotFound: ERROR
