server:
  port: 8763

spring:
  devtools:
    livereload:
      port: 35731
    restart:
      log-condition-evaluation-delta: false
  datasource:
    url: jdbc:mysql://localhost:${ENV_MYSQL_PORT:8762}/jwizard-db
  cloud:
    vault:
      uri: ${ENV_VAULT_URI:http://localhost:8761}
      token: ${ENV_VAULT_TOKEN}
      authentication: TOKEN
      kv:
        backend: jwizard
        default-context: common
        application-name: api
  config:
    import:
      - optional:vault://

jwizard:
  web:
    client-urls:
      - http://localhost:8764

logging:
  file:
    path: .log/dev
