server:
  port: 6061

spring:
  devtools:
    add-properties: false
  datasource:
    url: ${V_MYSQL_JDBC}
  cloud:
    vault:
      uri: ${JWIZARD_API_VAULT_SERVER}
      token: ${JWIZARD_API_VAULT_TOKEN}
      authentication: TOKEN
      kv:
        backend: jwizard
        default-context: common
        application-name: api
  config:
    import:
      - optional:vault://

jwizard:
  web:
    client-urls:
      - https://jwizard.pl

logging:
  file:
    path: .log/prod
