server:
  port: 6061

spring:
  devtools:
    add-properties: false
  datasource:
    url: jdbc:mysql://mysql2.small.pl:3306/m1486_jwizard
  cloud:
    vault:
      uri: https://vault.miloszgilga.pl
      token: ${JWIZARD_API_VAULT_TOKEN}
      authentication: TOKEN
      kv:
        backend: jwizard
        default-context: common
        application-name: api
  config:
    import:
      - optional:vault://

jwizard:
  web:
    client-urls:
      - https://jwizard.pl

logging:
  file:
    path: .log/prod
