server:
  port: 6061

spring:
  devtools:
    add-properties: false
  data:
    mongodb:
      host: mongo2.small.pl
      port: 27017
      database: mo1486_jwizard
  cloud:
    vault:
      uri: https://vault.miloszgilga.pl
      token: ${JWIZARD_API_VAULT_TOKEN}
      authentication: TOKEN
      kv:
        backend: jwizard
        default-context: common
        application-name: api
  config:
    import:
      - optional:vault://

jwizard:
  security:
    jwt-audience:
      standalone-client: proxy://standalone-prod
      web-client: https://jwizard.pl
    jwt-issuer: https://api.jwizard.pl
  guild:
    defaults:
      legacy-prefix: '$'
      inactivity:
        leave-empty-channel-sec-all:
          defined: 180
        leave-no-tracks-channel-sec-all:
          defined: 180

logging:
  file:
    path: .log/prod
