server:
  port: 8670

spring:
  devtools:
    livereload:
      port: 35731
    restart:
      log-condition-evaluation-delta: false

jwizard:
  security:
    jwt-audience:
      standalone-client: proxy://standalone-dev
      web-client: http://localhost:5173
    jwt-issuer: http://localhost:${server.port}
  guild:
    defaults:
      legacy-prefix: '?'

logging:
  file:
    path: .log/dev
