server:
  port: 8765
  self-url: http://localhost:8765

discord:
  process:
    url-fragment: http://localhost:%s
  oauth:
    redirect-url:
      success: http://localhost:8764
      error: http://localhost:8764/login?error=%s
    cookie:
      domain: localhost

cors:
  urls:
    - http://localhost:8763
    - http://localhost:8764
