server:
  port: 6061
  self-url: https://api.jwizard.pl

discord:
  process:
    url-fragment: https://bot-instance-%s-f%st%s.jwizard.pl
  oauth:
    redirect-url:
      success: https://dashboard.jwizard.pl
      error: https://dashboard.jwizard.pl/login?error=%s

cors:
  urls:
    - https://jwizard.pl
    - https://dashboard.jwizard.pl
