vault:
  kv:
    application-names:
      - api

server:
  port: ${vault:V_SERVER_PORT:8080}
  aes-secret-key: ${vault:V_AES_SECRET_KEY}

github:
  api:
    url: https://api.github.com
    token: ${vault:V_GITHUB_TOKEN}
  language-color-api-url: https://raw.githubusercontent.com/ozh/github-colors/master/colors.json

discord:
  api:
    url: https://discord.com/api/v10
  oauth:
    app-id: ${vault:V_DISCORD_OAUTH_APP_ID}
    app-secret: ${vault:V_DISCORD_OAUTH_SECRET}
    scopes:
      - identify
    session_ttl_sec: 604800 # 7 days
    sid-token-length: 32 # in bytes
    csrf-token-length: 32 # in bytes

lavalink:
  api:
    version: v4

cache:
  invalidate-time-sec: 10800 # 3h
  max-elements: 400
